### ISSUE TITLE
Hamburger not opening?

### ISSUE THREAD

**Issue by davronkhamdamov** [davronkhamdamov/reimagined-adventure#1]
![image](https://github.com/davronkhamdamov/reimagined-adventure/assets/109721370/06f1d47a-2112-4c31-8fb8-7369eafe4de2)
Hamburger not working

```css
* {
    scroll-behavior: smooth;
}

div {
    width: 1440px;
    height: 500px;
    background: red;
    overflow-x: scroll;
}

div::-webkit-scrollbar {
    height: 100px;
    background-color: blue;
}

div::-webkit-scrollbar-thumb {
    border-radius: 50%;
    background-color: green;
}

section {
    width: 15555px;
    display: flex;
}
```

**Comment by davronkhamdamov** [comment]
```css
* {
    scroll-behavior: smooth;
}

div {
    width: 1440px;
    height: 500px;
    background: red;
    overflow-x: scroll;
}

div::-webkit-scrollbar {
    height: 100px;
    background-color: blue;
}

div::-webkit-scrollbar-thumb {
    border-radius: 50%;
    background-color: green;
}

section {
    width: 15555px;
    display: flex;
}
```

**Comment by davronkhamdamov** [comment]
> ![image](https://private-user-images.githubusercontent.com/109721370/299640950-06f1d47a-2112-4c31-8fb8-7369eafe4de2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxODIyMDksIm5iZiI6MTcwNjE4MTkwOSwicGF0aCI6Ii8xMDk3MjEzNzAvMjk5NjQwOTUwLTA2ZjFkNDdhLTIxMTItNGMzMS04ZmI4LTczNjllYWZlNGRlMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyNVQxMTI1MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMWQzYmQxODk1ZDhiNjcwN2U1ZDExOTg3N2Q2MjQzNDZkMmY0N2VmNGFlY2M1YjVkNWE4NGRkM2M2OWMxZjVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-5hYuDPgINCqRJ_4ez4Jg3oS2TLiZ2SEU1d1fUYnn30) Hamburger not working
> 
> ```css
> * {
>     scroll-behavior: smooth;
> }
> 
> div {
>     width: 1440px;
>     height: 500px;
>     background: red;
>     overflow-x: scroll;
> }
> 
> div::-webkit-scrollbar {
>     height: 100px;
>     background-color: blue;
> }
> 
> div::-webkit-scrollbar-thumb {
>     border-radius: 50%;
>     background-color: green;
> }
> 
> section {
>     width: 15555px;
>     display: flex;
> }
> ```

```css
* {
    scroll-behavior: smooth;
}

div {
    width: 1440px;
    height: 500px;
    background: red;
    overflow-x: scroll;
}

div::-webkit-scrollbar {
    height: 100px;
    background-color: blue;
}

div::-webkit-scrollbar-thumb {
    border-radius: 50%;
    background-color: green;
}

section {
    width: 15555px;
    display: flex;
}
```
